### ISSUE TITLE
Contract Execution failed

### ISSUE THREAD

**Issue by dilukangelosl** [Babajikumaresan/MEV-Tools#2]
https://etherscan.io/tx/0x8645985329cc804af56a46f30681c015d25113706ba586d73a23561601e4c454

**Comment by Babajikumaresan** [comment]
Nice. Code is working fine and send order to the block chain. Transaction may fail in Eth block chain depends on gas / token.

you are calling 0x6e5c0B204D8c5311687513f0E71c10cB9e114B6b . 

The address for PEPE token pool you are sending transaction ,don't have any token. Check the correct PEPE/WETH pool address and run the code. else the transaction will fail.

**Comment by dilukangelosl** [comment]
which variables should be changed for this to work

**Comment by Babajikumaresan** [comment]
send me which pepe_eth_pair_address,uniswap_v3_router_address you are using ?

**Comment by Babajikumaresan** [comment]
pepe_eth_pair_address = "0x11950d141ecb863f01007add7d1a342041227b58"
uniswap_v3_router_address = "0xE592427A0AEce92De3Edee1F18E0157C05861564"
weth_address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"

this are the address given in the code are valid.

check it in the ethscan,then run the code. 
Note : Ethereum cost lot in gas

Wish you good luck.

**Comment by dilukangelosl** [comment]
even though pepe_eth_pair_address variable is there, its not used anywhere on the code

**Comment by Babajikumaresan** [comment]
Got it . Recent version will call the pepe_token_address and pepe_token_abi , then send it to Uniswap router to get the best liquidity to address the pool got dried out.
but i checked the ethscan transaction , uniswap send your iorder to PEPE5 liquidity pool. but the time it sent already token got over and only around 3000 token in pepe left.

 Then the order might be failed because of Gas. 

check the gas level from ethscan and change the reuired value in

 "fee": 500,  # Use the appropriate fee tier (500, 3000, or 10000)
and "gas": int(250000),  # Set an appropriate gas limit
